### ISSUE TITLE
Add SQLException  handling

### ISSUE THREAD

**Issue by FMAOuroboros** [christophd/citrus-db#3]
It should be possible to:

- Specify under which conditions a SQLException should be thrown
- Server exceptions should be forwarded as SQLException to the driver

**Comment by FMAOuroboros** [comment]
- Merge `thenThrow` with `thenRefuse`
- `thenRefuse` accepts no parameter or a `Exception` instance
- If the rule states, that the exception should be thrown, the exception is transmitted to the driver and then returned as the cause of an SQLException

**Comment by FMAOuroboros** [comment]
First of all, this feature will be implemented in the embedded version of citrus-db and not within the standalone one

**Comment by FMAOuroboros** [comment]
Hi!
The functionality of simulating exceptions is already available in the embedded variant.

```java
@Test
@CitrusTest
public void testRollback() {
    variable("todoName", "citrus:concat('todo_', citrus:randomNumber(4))");
    variable("todoDescription", "Description: ${todoName}");

    http()
            .client(todoClient)
            .send()
            .post("/todolist")
            .fork(true)
            .contentType("application/x-www-form-urlencoded")
            .payload("title=${todoName}&description=${todoDescription}");

    ...

    send(jdbcServer)
            .message(JdbcMessage.result().exception("Could not execute something"));

   ...
}
```

This results in a `SQLException` containing the specified message.
```
Caused by: java.sql.SQLException: Failed to execute update: Could not execute something
        at com.consol.citrus.db.driver.JdbcStatement.executeUpdate(JdbcStatement.java:96) ~[citrus-db-driver-0.1-SNAPSHOT.jar:na]
        at com.consol.citrus.db.driver.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:49) ~[citrus-db-driver-0.1-SNAPSHOT.jar:na]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
        at com.consol.citrus.samples.todolist.dao.JdbcTodoListDao.save(JdbcTodoListDao.java:44) ~[classes/:na]
        ... 91 common frames omitted
```

So due to the fact that the embedded variant is already able to simulate exceptions, I'll remove this issue from the milestone, because the standalone exception simulation is currently not in focus but should be implemented later on.
